services:
  proxy:
    container_name: kip-proxy
    restart: always
    image: ghcr.io/nicrozj/kip-proxy:latest
    networks:
      - docker_network
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./data/caddy:/data/caddy
      
networks:
  docker_network:
    external: true